### PR TITLE
workaround for failing WRITE_MILTIPLE_BLOCK calls

### PR DESCRIPTION
**Pull request by yetzt**
using WRITE_MILTIPLE_BLOCK fails with one of my sd cards, i made this workaround to use multiple calls of WRITE_BLOCK instead. default behaviour is not changed. this adresses #25

### CODE REVIEW

**Comment by natevw** [comment]
Hi, sorry took me a bit to get to this. The code looks good, the only thing would be can you rename the user-facing option name to `singleWrites` or something similar?

Especially given the performance impact (in the already very slow environment), I wouldn't want people getting worried about the default being "unsafe" and opt-ing into this even if they don't really need it.

**Comment by yetzt** [comment]
sure, here you go. :)

**Comment by yetzt** [comment]
ping.

**Comment by natevw** [comment]
Whoops, totally dropped the ball on this one, sorry :-/

**Pull request merged**
